// Code generated by tygo. DO NOT EDIT.
/* eslint-disable */
// Do not edit this file manually. It was auto-generated by Tygo.
//////////
// source: event_client.go

export interface Event {
  id: number /* int64 */;
  title: string;
  description: string;
  slug: string;
  date: string;
  host_id: number /* int64 */;
  image_url?: string;
  member_ids?: number /* int64 */[]; // used only when creating an event
  members?: JSONSlice<EventMember>; // enriched attendees, populated only when reading an event
  stops?: JSONSlice<EventStop>;
}
export interface EventStop {
  id: number /* int64 */;
  event_id: number /* int64 */;
  sort_id: number /* int64 */;
  name: string;
  address: string;
  latitude: number /* float64 */;
  longitude: number /* float64 */;
  stop_member_status_arr: JSONSlice<StopMemberStatus>;
}
export type RSVPStatus = "pending" | "accepted" | "declined"

export interface EventMember {
  user: User;
  rsvp_status: RSVPStatus;
  status_updated_at?: string;
  created_at: string;
}
export type StopStatus = "not_started" | "on_the_way" | "arrived" | "no_show"

export interface StopMemberStatus {
  user_id: number /* int64 */;
  stop_id: number /* int64 */;
  stop_status: StopStatus;
  status_updated_at: string;
}

//////////
// source: invite_client.go

export interface Invite {
  event: Event;
  host_user: User;
  event_member: EventMember;
}
/**
 * InviteLists separates a user's invites into ones they've received (pending on them
 * to RSVP) and ones they've sent (as the host of the event).
 */
export interface InviteLists {
  pending: Invite[];
  sent: Invite[];
}

//////////
// source: users_client.go

/**
 * The json:omitempty tag tells Go to exclude the field from
 * the generated JSON output when sending the result to the client
 * For javascript frontend apps, this effectiely makes the field undefined
 */
export interface User {
  id: number /* int64 */;
  clerk_id: string;
  username: string;
  first_name: string;
  last_name: string;
  email: string;
  image_url?: string;
  created_at?: string;
  updated_at?: string;
}

//////////
// source: utils.go

/**
 * JSONSlice lets a []T field scan directly from a json/jsonb column.
 */
export type JSONSlice<T extends any> = T[];
